---
release:
  prerelease: auto

changelog:
  skip: true

signs:
  - artifacts: checksum

builds:
  - binary: adventofcode
    main: cmd/adventofcode/main.go
    env:
      - CGO_ENABLED=0

archives:
  - files:
    - LICENSE.txt
    - README.md
    - CHANGELOG.md
    - input/*.txt
