---
name: solutions

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: goreleaser/goreleaser-action@v3
        with:
          args: build --single-target --snapshot
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: adventofcode
          path: dist/adventofcode-2017-go_linux_amd64_v1/adventofcode
          retention-days: 2
  solve:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: adventofcode
      - name: Fix permission
        run: chmod u+x adventofcode
      - name: Solve
        run: ./adventofcode
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solutions
          path: solutions
          retention-days: 2
